// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjF9yWOErLZ1VUFTqWsc5-mINUNpZpEwg',
    appId: '1:787353394095:web:85aba9471973ccf5a92d5a',
    messagingSenderId: '787353394095',
    projectId: 'backroads-foundation',
    authDomain: 'backroads-foundation.firebaseapp.com',
    storageBucket: 'backroads-foundation.appspot.com',
    measurementId: 'G-2JY1QSD579',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApq9YZpLNSq7GxfbmY-blkDnvSYWRtmJU',
    appId: '1:787353394095:android:337708c56649d771a92d5a',
    messagingSenderId: '787353394095',
    projectId: 'backroads-foundation',
    storageBucket: 'backroads-foundation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR9MV87syslaiYbbDLbPBOHmCsdMDbplU',
    appId: '1:787353394095:ios:bfdb77508bd1a9d2a92d5a',
    messagingSenderId: '787353394095',
    projectId: 'backroads-foundation',
    storageBucket: 'backroads-foundation.appspot.com',
    iosClientId: '787353394095-8p4p42tre4aot6731dro6fgicho7klpk.apps.googleusercontent.com',
    iosBundleId: 'com.backroadsfoundation.app',
  );
}
